spring:
  profiles:
    active: docker
  application:
    name: nota-fiscal-worker
  rabbitmq:
    listener:
      simple:
        retry:
            enabled: true
            max-attempts: 3
            initial-interval: 10000
            max-interval: 30000
            multiplier: 2
app:
  myport: ${PORT:0}
server:
  port: ${app.myport}