#spring:
#  application:
#    name: nota-fiscal-worker
#  rabbitmq:
#    listener:
#      simple:
#        retry:
#            enabled: true
#            max-attempts: 3
#            initial-interval: 10000
#            max-interval: 30000
#            multiplier: 2
#server:
#  port: 8080

spring:
  application:
    name: nota-fiscal-worker
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 10000
          max-interval: 30000
          multiplier: 2
server:
  port: 8080
