spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: cobranca-service

server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://EUREKA-SERVICE:8761/eureka