spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: catalogo
          uri: lb://CATALOGO-SERVICE
          predicates:
            - Path=/catalogo/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                  retries: 3
                  methods: GET, POST
                  backoff:
                    initialInterval: 300ms
                    maxInterval: 2s
                    multiplier: 2

        - id: locacao
          uri: lb://LOCACAO-SERVICE
          predicates:
            - Path=/locacao/**
          filters:
            - StripPrefix=1
            - name: UserAuthentication
              args:
                headerName: Authorization

        - id: cobranca
          uri: lb://COBRANCA-SERVICE
          predicates:
            - Path=/cobranca/**
          filters:
            - StripPrefix=1

        - id: cliente
          uri: lb://CLIENTE-SERVICE
          predicates:
            - Path=/cliente/**
          filters:
            - StripPrefix=1

        - id: avaliacao
          uri: lb://AVALIACAO-SERVICE
          predicates:
            - Path=/avaliacao/**
          filters:
            - StripPrefix=1

server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG