spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: catalogo
          uri: lb://CATALOGO-SERVICE
          predicates:
            - Path=/catalogo/**
          filters:
            - StripPrefix=1

server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG