version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - acme

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    networks:
      - acme

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./conf/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - acme

  notafiscaldb:
    image: postgres:latest
    container_name: notafiscaldb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notafiscal
    networks:
      - acme

  eureka-service:
    container_name: EUREKA-SERVICE
    image: moisesreis/eureka:latest
    ports:
      - "8761:8761"
    networks:
      - acme

  config-server:
    container_name: config-server
    image: moisesreis/config-server:latest
    environment: 
      - GITHUB_TOKEN=
    depends_on:
      - eureka-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - acme

  gateway-service:
    container_name: gateway-service
    image: moisesreis/gateway:latest
    ports:
      - "9999:9999"
    networks:
      - acme
    depends_on:
      - eureka-service

  cobranca-service:
    container_name: cobranca-service
    image: moisesreis/cobranca:latest
    networks:
      - acme
    depends_on:
      config-server:
        condition: service_healthy

  cliente-service:
    container_name: cliente-service
    image: moisesreis/cliente:latest
    networks:
      - acme
    depends_on:
      - eureka-service

  catalogo-service:
    container_name: catalogo-service
    image: moisesreis/catalogo:latest
    networks:
      - acme
    depends_on:
      - eureka-service

  nota-fiscal-service:
    container_name: nota-fiscal-service
    image: moisesreis/nota-fiscal:latest
    networks:
      - acme
    depends_on:
      - eureka-service
      - notafiscaldb
      - rabbitmq

  locacao-service:
    container_name: locacao-service
    image: moisesreis/locacao:latest
    networks:
      - acme
    depends_on:
      - eureka-service
      - mongodb

  avaliacao-service:
    container_name: avaliacao-service
    image: moisesreis/avaliacao:latest
    networks:
      - acme
    depends_on:
      - eureka-service

volumes:
  mongo-data:
    driver: local

networks:
  acme:
    driver: bridge
    external: true
