version: '3.8'

services:
  locacaodb:
    image: mongo:7-jammy
    container_name: locacaodb
    volumes:
      - mongo-data:/data/db
    networks:
      - acme

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: locacaodb
    ports:
      - 8081:8081
    depends_on:
      - locacaodb
    networks:
      - acme

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./conf/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - acme

  notafiscaldb:
    image: postgres:latest
    container_name: notafiscaldb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notafiscal
    networks:
      - acme

  usuariosdb:
    image: mariadb:latest
    container_name: usuariosdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: usuarios
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - acme

  eureka-service:
    container_name: EUREKA-SERVICE
    image: moisesreis/eureka:latest
    ports:
      - "8761:8761"
    networks:
      - acme

  config-server:
    container_name: config-server
    image: moisesreis/config-server:latest
    environment: 
      - GITHUB_TOKEN=
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - acme
    depends_on:
      - eureka-service

  gateway-service:
    container_name: gateway-service
    image: moisesreis/gateway:latest
    ports:
      - "9999:9999"
    networks:
      - acme
    depends_on:
      - eureka-service

  cobranca-service:
    container_name: cobranca-service
    image: moisesreis/cobranca:latest
    networks:
      - acme
    depends_on:
      config-server:
        condition: service_healthy

  cliente-service:
    container_name: cliente-service
    image: moisesreis/cliente:latest
    networks:
      - acme
    depends_on:
      - eureka-service

  catalogo-service:
    container_name: catalogo-service
    image: moisesreis/catalogo:latest
    networks:
      - acme
    depends_on:
      - eureka-service

  nota-fiscal-service:
    container_name: nota-fiscal-service
    image: moisesreis/nota-fiscal:latest
    networks:
      - acme
    depends_on:
      - eureka-service
      - notafiscaldb
      - rabbitmq

  locacao-service:
    container_name: locacao-service
    image: moisesreis/locacao:latest
    networks:
      - acme
    depends_on:
      - eureka-service
      - locacaodb

  avaliacao-service:
    container_name: avaliacao-service
    image: moisesreis/avaliacao:latest
    networks:
      - acme
    depends_on:
      - eureka-service

  nota-fiscal-worker:
    container_name: nota-fiscal-worker
    image: moisesreis/nota-fiscal-worker:latest
    networks:
      - acme
    depends_on:
      - nota-fiscal-service
      - rabbitmq

  auth-service:
    container_name: auth-service
    image: moisesreis/auth-service:latest
    ports:
      - "9997:9997"
    networks:
      - acme
    depends_on:
      - eureka-service
      - usuariosdb

volumes:
  mongo-data:
    driver: local
  mariadb_data:
    driver: local

networks:
  acme:
    driver: bridge
    external: true
