spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/locacao
  application:
    name: locacao-service

server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://EUREKA-SERVICE:8761/eureka