server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bkmoises/acme-not-config
          clone-on-start: true
          search-paths:
            - "config"
          username: bkmoises
          password: ${GITHUB_TOKEN}